# Generated by Django 5.2.1 on 2025-05-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caera", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposal",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
