# Generated by Django 5.2.1 on 2025-06-02 08:18

import caera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caera", "0005_proposal_city"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="image_url",
        ),
        migrations.AddField(
            model_name="proposal",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=caera.models.proposal_image_file_path
            ),
        ),
    ]
