# Generated by Django 5.2.1 on 2025-06-02 10:09

import caera.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caera", "0006_remove_proposal_image_url_proposal_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="image_url",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=caera.models.proposal_image_file_path
            ),
        ),
    ]
